# define the language of this project
language: node_js

# define node.js versions to run on
node_js:
  - "stable"
  - "7"
  - "6"

# run before everey other script
before_script:
  - npm install

# run some scripts
script:
  # run lint
  - npm run-script lint

  # run tests
  #- npm run-script test-travis

# trigger some additional tools after success
# after_success:
#   # send coverage data to coveralls
#   - npm run-script coveralls
