# define the language of this project
language: node_js

# define node.js versions to run on
node_js:
  - "stable"
  - "12"
  - "10"

# run before everey other script
before_script:
  - npm install

# run some scripts
script:
  # run lint
  - npm run lint

  # run tests
  #- npm run test-travis

# trigger some additional tools after success
# after_success:
#   # send coverage data to coveralls
#   - npm run coveralls
